# Generated by Django 3.2.9 on 2021-12-22 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='name',
        ),
        migrations.RemoveField(
            model_name='game',
            name='type',
        ),
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='levelupapi.gametype'),
        ),
        migrations.AddField(
            model_name='game',
            name='gamer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='levelupapi.gamer'),
        ),
        migrations.AddField(
            model_name='game',
            name='maker',
            field=models.CharField(default='None', max_length=75),
        ),
        migrations.AddField(
            model_name='game',
            name='number_of_players',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='skill_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='title',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
