# Generated by Django 3.2.9 on 2022-01-15 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0003_auto_20220108_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamer',
            old_name='gamer',
            new_name='user',
        ),
    ]
